### ISSUE TITLE
PyPI release needs adjustment in install_requires

### ISSUE THREAD

**Issue by Grumium** [mlerotic/spectromicroscopy#11]
https://github.com/mlerotic/spectromicroscopy/blob/1294e915b8cadf3efd16dd6dbaac73ade9cd81f8/setup.py#L20

Pyqtgraph in versions >0.12.4 breaks the "Image map" functionality in the master branch and in the official release on PyPI. So fresh installs do not work as expected. Users currently need to downgrade via `pip install pyqtgraph==0.12.4 --force-reinstall`.

I suggest the following work around for the moment until the development branch is fully integrated into the official release. 
`install_requires=['PyQt5','numpy', 'scipy', 'matplotlib', 'h5py', 'Pillow', 'lxml', 'pyqtgraph<=0.12.4', "scikit-image"],`

This issue doesn't affect the development branch.

Cheers
JD

**Comment by mlerotic** [comment]
Sounds good! :)

**Comment by Grumium** [comment]
Could you or @benajamin please take care of the PyPI release when you find some time? I don't have the privileges. Thanks. ;)

**Comment by mlerotic** [comment]
Hm, I am not sure how to do this. Either Ben did this or I forgot. ;). Ben,
do you have time to create a new Pip release? If not, let me know and I'll
figure it out.

**Comment by benajamin** [comment]
fixed in version 3.1.10, commit f5caf02ec11e2100d968b2552737a0bd3d45c7f3
