### ISSUE TITLE
Feature Request: Image map - Background bar

### ISSUE THREAD

**Issue by MrDevil13** [mlerotic/spectromicroscopy#15]
Hi, 

In the Image map mode, Is it possible to add the a third bar which can be used as a background?

**Comment by Grumium** [comment]
I am not sure what you mean. Could you provide more context about what you're asking, like a screenshot? Which version are you using?

**Comment by MrDevil13** [comment]
I am using Mantis v3.1.15. I am referring to the operation that can be done from the first image. As you can see here, I can only set the pre and post-edge regions. However, in order to identify the various species from a spectrum, I need to subtract the pre-edge background, which is not provided in this version. Is it possible to add this feature? 
![mantis](https://github.com/mlerotic/spectromicroscopy/assets/134031278/5906453d-2b3e-41cd-8e6e-6ba1cd92505c)
![1-s2 0-S0368204823000270-gr6_lrg](https://github.com/mlerotic/spectromicroscopy/assets/134031278/7f80a8f9-f06e-4203-a163-48040f7b810b)

**Comment by MrDevil13** [comment]
By adding this feature it would be helpful in identifying the valence mapping by summing OD within peaks, As you see from the image Map below in which the green channel represents the intensity in the first peak of the L3 edge, blue, the second peak, and red the average OD over a wide band, which mostly indicates background species. 
![1-s2 0-S0368204823000270-gr7_lrg](https://github.com/mlerotic/spectromicroscopy/assets/134031278/37b1935c-9089-4a70-8cef-f0eeb637ec20)

**Comment by Grumium** [comment]
There are dedicated tools within MANTiS to perform the tasks you've described. Please refer to the following links for spectral unmixing:

- Spectral Maps Tab: https://docs.spectromicroscopy.com/#spectral-maps-tab
- NNMA Analysis Tab: https://docs.spectromicroscopy.com/#nnma-analysis-tab

This functionality is beyond the scope of the OD mapping tool, which is designed to generate spatial distribution maps by combining "I_0" and "I" data.

Therefore, adding a third regional selector to the OD mapping tool doesn't make sense, as it would require a new color scale for each spectral feature you wish to visualize. (Having more than three features would already cause issues in an RGB color space.) However, to highlight the spatial distribution of valence states using the "Image maps/OD mapping" tool, now located under "Spectral ROI" in recent development versions, you can:

- Create two or more OD maps and combine them in external software, adjusting colors as needed (e.g., see https://doi.org/10.1016/j.chemgeo.2017.04.009 Fig. 9fff), or
- Utilize a diverging color scheme (e.g., see https://pubs.acs.org/doi/10.1021/acs.jpcc.1c03600 Fig. 6)

Tip: You can select or deselect individual energies from your chosen regions by using the left and right mouse buttons on the list of images/energies, allowing you to also include images in the "valley" between two spectral features or to define a discontinuous I or I_0 region.
