### ISSUE TITLE
Issue _ Mantis v.3.1.38

### ISSUE THREAD

**Issue by edoelsch** [mlerotic/spectromicroscopy#17]
Hi,
I just installed Miniconda and Mantis following the Installation Guide written by JD Förster.
I'm encountering an issue when opening the data. After selecting the data (data that I can open with version 3.1.15), the cursor becomes the blue spinning wheel indicating it's busy. In the 'Preprocess Data' window, no options are available (Align stack, etc.)

Do you have any idea to solve this issue ?
Thank you in advance

Emmanuel

![image](https://github.com/mlerotic/spectromicroscopy/assets/169818090/4ecd626e-7f0b-4471-8bf1-f0bf863641ac)

**Comment by Grumium** [comment]
Hi. I can confirm this error. There have been breaking changes in pyqtgraph>0.13.3.
A temporary fix is downgrading pyqtgraph. `pip install pyqtgraph==0.13.3`.
Future releases will be limited to pyqtgraph>=0.13.7.
I will push a new version asap.

Cheers,
Jan-David

**Comment by Grumium** [comment]
This has been fixed in development branch version 3.1.40 https://github.com/mlerotic/spectromicroscopy/commit/b992276a86f6763855a34125fdcf78fd9490efa5
