### ISSUE TITLE
Deprecated scipy.dot in mantis-xray

### ISSUE THREAD

**Issue by RAHLIOussama962** [mlerotic/spectromicroscopy#23]
The mantis-xray application crashes due to the use of the deprecated scipy.dot function, which has been removed in recent versions of scipy. This results in an AttributeError. Replacing it with numpy.dot would fix the issue and ensure compatibility with newer scipy versions.

  File "/usr/lib/python3/dist-packages/mantis_xray/mantis_qt.py", line 63, in <module>
    from . import analyze
  File "/usr/lib/python3/dist-packages/mantis_xray/analyze.py", line 32, in <module>
    mmult = sp.dot
            ^^^^^^
  File "/usr/lib/python3/dist-packages/scipy/__init__.py", line 139, in __getattr__
    raise AttributeError(
AttributeError: Module 'scipy' has no attribute 'dot'

Thank you for your attention to this issue!

**Comment by Grumium** [comment]
This is a duplicate. Please use the development branch or downgrade your scipy to the version suggested,
https://github.com/mlerotic/spectromicroscopy/issues/13#issuecomment-1959212583
