### ISSUE TITLE
AttributeError: 'analyze' object has no attribute 'numsigpca'

### ISSUE THREAD

**Issue by urquhart-usask** [mlerotic/spectromicroscopy#25]
I'm not sure if this is a PEBKAC error [1] or something weird in the Mantis updates. I've been using Mantis for PCA and CA analysis for a while, but messed up my installation so I reinstalled the current version.

I am loading a pre-existing OD image sequence in ncb format that I have previously used in Mantis. I load the image sequent, and select 'use pre-processed data' under the pre-process data tab. I then select 'calculate PCA' under the PCA tab.

Under mantis-xray version 3.2.1, I get the following error:

```
pca not converging
Traceback (most recent call last):
File "/Users/urquhart/Documents/calculations/mantis/venv/lib/python3.12/site-packages/mantis_xray/mantis_qt.py", line 8194, in OnCalcPCA
self.CalcPCA()
File "/Users/urquhart/Documents/calculations/mantis/venv/lib/python3.12/site-packages/mantis_xray/mantis_qt.py", line 8293, in CalcPCA
self.numsigpca = self.anlz.numsigpca
^^^^^^^^^^^^^^^^^^^
AttributeError: 'analyze' object has no attribute 'numsigpca'
```

I went to install the n-1 version of mantis, using:
`pip install mantis-xray==3.1.15`

and made the corrections for the np.dot and trapz issues. This version had worked for me previously ... although I don't know if specifying '3.1.15' gives me the same code as what I installed previously.

I get the same error:

```
pca not converging
Traceback (most recent call last):
File "/Users/urquhart/Documents/calculations/mantis/venv/lib/python3.12/site-packages/mantis_xray/mantis_qt.py", line 8184, in OnCalcPCA
self.CalcPCA()
File "/Users/urquhart/Documents/calculations/mantis/venv/lib/python3.12/site-packages/mantis_xray/mantis_qt.py", line 8282, in CalcPCA
self.numsigpca = self.anlz.numsigpca
^^^^^^^^^^^^^^^^^^^
AttributeError: 'analyze' object has no attribute 'numsigpca'
```

Perhaps an error was introduced that is getting caught up in the '==3.1.15' install, or a PEBKEC error.[1]

thanks,
Stephen

1. PEBKEC = 'problem exists between keyboard and chair'

**Comment by Grumium** [comment]
I just tested it and I don't run into this error. Could you please tell me all the package versions you are using?

**Comment by urquhart-usask** [comment]
pip list gives me the following:

```
Package         Version
--------------- -----------
contourpy       1.3.0
cycler          0.12.1
fonttools       4.54.1
h5py            3.12.1
imageio         2.35.1
kiwisolver      1.4.7
lazy_loader     0.4
lxml            5.3.0
mantis-xray     3.1.15
matplotlib      3.9.2
networkx        3.3
numpy           2.1.1
packaging       24.1
pillow          10.4.0
pip             24.2
pyparsing       3.1.4
PyQt5           5.15.11
PyQt5-Qt5       5.15.15
PyQt5_sip       12.15.0
pyqtgraph       0.12.4
python-dateutil 2.9.0.post0
scikit-image    0.24.0
scipy           1.14.1
six             1.16.0
tifffile        2024.9.20
```

I'm running in a python environment.

I can roll back a version easily, so let me know if I should try something.

thanks!

**Comment by Grumium** [comment]
Could you please go back to mantis 3.2.1 and post this again? At least pyqtgraph in this version is incompatible with the new version.

**Comment by Grumium** [comment]
Oh and please downgrade to numpy==1.26.4

Yes, it has to do with the major changes in numpy > 2.0.0
At least your problem disappears when using numpy==1.26.4.

**Comment by urquhart-usask** [comment]
That's it - mantis 3.2.1 works with numpy 1.26.4

thank you!

**Comment by Grumium** [comment]
This is just a workaround. However, I need to see what the breaking changes are and provide a fix. Thanks for pointing this out!

**Comment by Grumium** [comment]
Fixed in https://github.com/mlerotic/spectromicroscopy/commit/097affb37dee13ab708152f4b20cdae0e6277d15

**Comment by Grumium** [comment]
@urquhart-usask 
New version on PyPi compatible with numpy > 2:
https://pypi.org/project/mantis-xray/
