### ISSUE TITLE
Bug: Import Cluster Spectra to Peak Fit

### ISSUE THREAD

**Issue by DCSteelie** [mlerotic/spectromicroscopy#27]
Hi there, I am enjoying the latest version of MANTIS. I had an issue with the Numpy version initially but the newest release has solved that. However, I cannot import spectra from either the Cluster analyses or import a saved file into the peak fitting part of the software. I wondered if that was something that could be addressed. Thanks again for all your work on the software.

**Comment by Grumium** [comment]
Thank you for your kind words. Yes, sure. I will look into it asap. This is a core feature and it should definitely work.

**Comment by DCSteelie** [comment]
Thanks so much
Best
Steelie

**Comment by Grumium** [comment]
"Add cluster spectra" is working again.  https://github.com/mlerotic/spectromicroscopy/commit/032f77c5686dd8007d4720816493c6a376560c9d
I'm still fixing the "Load spectrum".

**Comment by DCSteelie** [comment]
Brilliant thank you. Not to add to your list, I noticed that the histogram function to change the brightness and contrast in image maps is also not working. I just thought I would mention it, not complaining, i love this version of the software.

**Comment by Grumium** [comment]
> Brilliant thank you. Not to add to your list, I noticed that the histogram function to change the brightness and contrast in image maps is also not working. I just thought I would mention it, not complaining, i love this version of the software.

Hey, can you just open a new issue for that, please? It makes it easier for to keep track of the To-Dos. You refer to the "Histogram Value Cutoff", right?

**Comment by Grumium** [comment]
> "Add cluster spectra" is working again. [032f77c](https://github.com/mlerotic/spectromicroscopy/commit/032f77c5686dd8007d4720816493c6a376560c9d) I'm still fixing the "Load spectrum".

It took me a long time, but this has been resolved in https://github.com/mlerotic/spectromicroscopy/commit/2668ebf79e5fe448895a3d7cadecc7bd72d78cf9
