### ISSUE TITLE
new features not workinh

### ISSUE THREAD

**Issue by ghost** [mlerotic/spectromicroscopy#4]
Hi! The new feature **FFT cross-correlation alignment is **not** working for me**. I mean I click the button FFT and nothing happens so I end up using the old alignment that is an old feature.

**Comment by Grumium** [comment]
Hi! Please add some more information to your report, such as:
- \# commit / branch / version
- Installation route (PyPI, Git)
- Traceback in the terminal/console
- Which type of file did you attempt to process?

**Comment by ghost** [comment]
The steps I followed are the below:
1. Download the zip from https://github.com/mlerotic/spectromicroscopy.
2.  Put everything in the right path.
3.  Run the python code mantis_qt.py in my spyder editor.
4.  Load my STXM data. The file is hdr . It has xim files for each energy. Hence, it is an image stack. Everything is working fine. I checked with other compatible data as well.
5.  I clicked Align Stack. Then a window that says Choose an image registration tool: FFT cross-correlation and Manual alignment. When I click Manual alignment everything works properly but when I click FFT cross-correlation, nothing happens. 
6. I check my console to see if any mistake appears, but nothing appears as if the option FFT cross-correlation is not active yet.
7. I repeated the same process for Windows and Linux. The result is the same,

**Comment by Grumium** [comment]
Thanks!

- Invoking mantis_qt.py directly is not recommended. We recently switched from absolute to relative imports. Instead, please run Mantis as a module `python3 -m mantis-xray` from your console.
- Before you can run the module you need to install it. Make sure the package `setuptools` is installed. Run the setup.py file located inside the downloaded and extracted ZIP archive.  `python3 setup.py install`. This what `pip` usually does for you.

- If this does not work, just use the installation route we recommend in the documentation and install it via `pip install mantis-xray`: https://docs.spectromicroscopy.com/#installation
- If this does not work, could you please repeat your process and just download your ZIP file from the development branch instead of the master branch (Running setup.py for installation is still required!)?

**Comment by ghost** [comment]
Excuse my mistake. I downloaded the zip from https://github.com/mlerotic/spectromicroscopy/tree/development.
Thanks for the recommendation! Now I will run the setup.py for the development version, because I want the new feature FFT cross-correlation. Let's hope that there will not be any conflicts with my other packages.

**Comment by Grumium** [comment]
You're welcome. Just to be clear, if it is just about the new alignment: This is already included in the PyPI version. However, please feel encouraged to use the development branch. Also, creating a virtual environment (via venv or conda) might be a good idea to not accidentally break things.

**Comment by ghost** [comment]
Everything works fine with the recommended route. However, I am a bit confused about the versions.

1. Pip recommended installation leads to version 3.0.11.
2. Downloading development version leads to version 3.0.11 as anyway mentioned in the _init_ file. I did not have any issue with the absolute imports since I can just use sys to specify my path.

I see that in the master version it mentions that you are merging 3.1.01 version.

I would expect the development version to be the most recent one meaning the 3.1.01 version.
So the question is what should I download to have the version 3.1.01 now? Can you provide the link for the 3.1.01 version?
Should I download the master version to have the 3.1.01 version?

Thank you in advance and excuse me if the answer is obvious.

**Comment by ghost** [comment]
The master version seems to be the one with the most useful features version 3.1.01. What additional features should I expect so that I can be sure that everything is working ok?

**Comment by Grumium** [comment]
- Version numbers are maintained in the master branch and mean nothing in the development branch. I agree that we should be more concise in the development branch as well to avoid any confusion.
- The master branch 'should' be identical with the version on pip.
- The development branch provides the most recent features but can be considered unstable. As the name indicates, it is meant for developers (or very brave people). 
- The requested version 3.1.01 can be found in the subsequent commit: https://github.com/mlerotic/spectromicroscopy/tree/f4edb5c2ed2694a47b5537fc094ef2d9c3e57fec 
- Among many bugfixes, the FFT cross-correlation alignment is the main functional improvement therein. 
- However, to properly display icons, please use the recent commit from the master branch: https://github.com/mlerotic/spectromicroscopy/commit/26ac78655392729a1449514a9fb434a8ce0872fa

**Comment by ghost** [comment]
Thank you! The most recent features that I can see is the two region image map and the crop image. Other than that the master and the development are the same in terms of functional features.

**Comment by Grumium** [comment]
For completeness, the differences to the compiled versions currently involve 
- "Load Data" tab (including rotate/mirror data, support for single images, etc.)
- "Select I0" interface
- "Crop Stack 3D/4D" (crops data along the energy axis as well as spatial axes, allows single images to be removed from a stack)
- Artifacts & Leveling (remove common artifacts such as gradients and hot/dark pixels)
- "Image maps" tab (is going to replace Spectral ROI (already done in the recent version from yesterday))
- FFT cross-correlation alignment
