### ISSUE TITLE
Number of rows and columns of stack is switched?

### ISSUE THREAD

**Issue by ptim0626** [mlerotic/spectromicroscopy#9]
Hi, I have a stack that is `(32, 73, 100)` and using the `file_dataexch_hdf5.py` (the Exchange plugin), and I encountered an error in loading the file. The problematic line is [this](https://github.com/mlerotic/spectromicroscopy/blob/408c02aa40ebd5412506172c89737ce19832bf1b/mantis_xray/mantis_qt.py#L9850) and the error:
```
IndexError: index 36 is out of bounds for axis 0 with size 32
```

The reason is that it thinks 36 is for the first axis (y-axis), but it should be indexing the second axis (x-axis).

It seems like the root of the problem is when the stack gets its `n_cols` and `n_rows` attribute in [here](https://github.com/mlerotic/spectromicroscopy/blob/development/mantis_xray/file_plugins/file_dataexch_hdf5.py#L448-449), they are switched. Should `datadim[0]` be the number of row and `datadim[1]` the number of column? Switching this can make the above error disappeared, but causing more (a lot of initialisation depends on `n_cols` and `n_rows`). 

A brief look of the plugins seems all had the axes switched, in my opinion. Is this intended or I am misunderstanding something? Thanks.

**Comment by Grumium** [comment]
Hi. 
Yes, I can confirm that issue in the development branch. That particular `loadSpectrum` function is a remnant and should've never been called. The ways spectra are extracted and displayed were subject to major changes recently and apparently I didn't check the compatibility with the exchange plugin. I'll look into this. Meanwhile, try using the SDF or NXstxm plugins.

**Comment by Grumium** [comment]
An old development version has been used. The issue is not present in MANTiS v3.1.19 and above. Always make sure to use the recommended package versions. PyQt5 v5.15.7  was added as a compulsory prerequisite to `setup.py` in MANTiS v3.1.20 9bc7fd55dcbc9ec532f50fb741eaefd753482586
